import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "./context/useTheme";
import { SubLayout } from "./subLayout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Mayaki's Portfolio",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html
        lang="en"
        className={`${poppins.variable} font-sans`}
        suppressHydrationWarning
      >
        {/* <head>
          <script
            dangerouslySetInnerHTML={{
              __html: `
            (function () {
                  if (typeof window !== 'undefined' && typeof document !== 'undefined') {
              const storedTheme = sessionStorage.getItem("theme");
              const prefersLightMode = window.matchMedia("(prefers-color-scheme: light)").matches;
              const theme = storedTheme || (prefersLightMode ? "light" : "dark");
              const existingClasses = document.documentElement.className.split(" ");
              const filteredClasses = existingClasses.filter(
                 (cls) => cls !== "light" && cls !== "dark");
               document.documentElement.className = [...filteredClasses, theme].join(" ");
             }
            })();
          `,
            }}
          /> 
        </head> */}

        <SubLayout>{children}</SubLayout>
      </html>
    </ThemeProvider>
  );
}
